name: Release

on:
  push:
    branches:
      - release
    paths:
      - '.ci/docker-matrix.json'
      - '*.Dockerfile'
      - 'linux-*.Dockerfile'

permissions:
  contents: write
  packages: write
  pull-requests: write
  actions: read

concurrency:
  group: release-${{ github.repository }}
  cancel-in-progress: true

jobs:
  release:
    uses: runlix/build-workflow/.github/workflows/build-images-rebuild.yml@main
    with:
      pr_mode: false
    secrets: inherit
